# Generated by Django 5.2.5 on 2025-08-18 12:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=64, unique=True)),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Series',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parameter', models.CharField(choices=[('Tmax', 'Max temp'), ('Tmin', 'Min temp'), ('Tmean', 'Mean temp'), ('Sun', 'Sunshine'), ('Rain', 'Rainfall'), ('Raindays', 'Rain days >=1.0mm'), ('Frost', 'Days of air frost')], max_length=20)),
                ('year', models.IntegerField(db_index=True)),
                ('value', models.FloatField(blank=True, null=True)),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='series', to='metweather.region')),
            ],
            options={
                'ordering': ['-year'],
                'unique_together': {('region', 'parameter', 'year')},
            },
        ),
    ]
