# Generated by Django 5.2.5 on 2025-08-18 14:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metweather', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MonthlySeries',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parameter', models.CharField(choices=[('Tmax', 'Max temp'), ('Tmin', 'Min temp'), ('Tmean', 'Mean temp'), ('Sun', 'Sunshine'), ('Rain', 'Rainfall'), ('Raindays', 'Rain days >=1.0mm'), ('Frost', 'Days of air frost')], max_length=20)),
                ('year', models.IntegerField(db_index=True)),
                ('month', models.PositiveSmallIntegerField()),
                ('value', models.FloatField(blank=True, null=True)),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='monthly_series', to='metweather.region')),
            ],
            options={
                'ordering': ['region', 'parameter', 'year', 'month'],
            },
        ),
        migrations.DeleteModel(
            name='Series',
        ),
        migrations.AddIndex(
            model_name='monthlyseries',
            index=models.Index(fields=['region', 'parameter', 'year'], name='metweather__region__4344de_idx'),
        ),
        migrations.AddIndex(
            model_name='monthlyseries',
            index=models.Index(fields=['parameter', 'year', 'month'], name='metweather__paramet_fe20c8_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='monthlyseries',
            unique_together={('region', 'parameter', 'year', 'month')},
        ),
    ]
