# Generated by Django 5.2.5 on 2025-08-18 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metweather', '0002_monthlyseries_delete_series_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MonthlyWeatherData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('region', models.CharField(choices=[('UK', 'UK'), ('England', 'England'), ('Scotland', 'Scotland'), ('Wales', 'Wales'), ('Northern_Ireland', 'Northern Ireland')], max_length=50)),
                ('parameter', models.CharField(choices=[('Tmax', 'Maximum Temperature'), ('Tmin', 'Minimum Temperature'), ('Tmean', 'Mean Temperature'), ('Sunshine', 'Sunshine Hours'), ('Rainfall', 'Rainfall'), ('Raindays', 'Raindays')], max_length=20)),
                ('year', models.PositiveIntegerField()),
                ('jan', models.FloatField(blank=True, null=True)),
                ('feb', models.FloatField(blank=True, null=True)),
                ('mar', models.FloatField(blank=True, null=True)),
                ('apr', models.FloatField(blank=True, null=True)),
                ('may', models.FloatField(blank=True, null=True)),
                ('jun', models.FloatField(blank=True, null=True)),
                ('jul', models.FloatField(blank=True, null=True)),
                ('aug', models.FloatField(blank=True, null=True)),
                ('sep', models.FloatField(blank=True, null=True)),
                ('oct', models.FloatField(blank=True, null=True)),
                ('nov', models.FloatField(blank=True, null=True)),
                ('dec', models.FloatField(blank=True, null=True)),
            ],
            options={
                'ordering': ['region', 'parameter', 'year'],
                'unique_together': {('region', 'parameter', 'year')},
            },
        ),
        migrations.DeleteModel(
            name='MonthlySeries',
        ),
        migrations.DeleteModel(
            name='Region',
        ),
    ]
