# Generated by Django 5.2.5 on 2025-08-18 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metweather', '0003_monthlyweatherdata_delete_monthlyseries_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='monthlyweatherdata',
            options={},
        ),
        migrations.AlterField(
            model_name='monthlyweatherdata',
            name='parameter',
            field=models.CharField(choices=[('Tmax', 'Maximum Temperature'), ('Tmin', 'Minimum Temperature'), ('Tmean', 'Mean Temperature'), ('Sunshine', 'Sunshine'), ('Rainfall', 'Rainfall'), ('Raindays', 'Raindays ≥ 1mm')], max_length=20),
        ),
        migrations.AlterField(
            model_name='monthlyweatherdata',
            name='region',
            field=models.CharField(choices=[('UK', 'UK'), ('England', 'England'), ('Wales', 'Wales'), ('Scotland', 'Scotland'), ('Northern_Ireland', 'Northern Ireland')], max_length=50),
        ),
        migrations.AlterField(
            model_name='monthlyweatherdata',
            name='year',
            field=models.IntegerField(),
        ),
    ]
