# Generated by Django 5.2.5 on 2025-08-18 17:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metweather', '0005_monthlyseries_region_delete_monthlyweatherdata_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Parameter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=50, unique=True)),
                ('description', models.CharField(blank=True, max_length=200)),
            ],
        ),
        migrations.AlterModelOptions(
            name='monthlyseries',
            options={},
        ),
        migrations.RemoveIndex(
            model_name='monthlyseries',
            name='metweather__region__4344de_idx',
        ),
        migrations.RemoveIndex(
            model_name='monthlyseries',
            name='metweather__paramet_fe20c8_idx',
        ),
        migrations.AlterField(
            model_name='monthlyseries',
            name='month',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='monthlyseries',
            name='parameter',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='monthlyseries',
            name='region',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='metweather.region'),
        ),
        migrations.AlterField(
            model_name='monthlyseries',
            name='year',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='region',
            name='code',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='region',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
