# Generated by Django 5.2.5 on 2025-08-18 18:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metweather', '0006_parameter_alter_monthlyseries_options_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Parameter',
        ),
        migrations.AlterModelOptions(
            name='monthlyseries',
            options={'ordering': ['region', 'parameter', 'year', 'month']},
        ),
        migrations.AlterField(
            model_name='monthlyseries',
            name='month',
            field=models.PositiveSmallIntegerField(),
        ),
        migrations.AlterField(
            model_name='monthlyseries',
            name='parameter',
            field=models.CharField(choices=[('Tmax', 'Max temp'), ('Tmin', 'Min temp'), ('Tmean', 'Mean temp'), ('Sun', 'Sunshine'), ('Rain', 'Rainfall'), ('Raindays', 'Rain days >=1.0mm'), ('Frost', 'Days of air frost')], max_length=20),
        ),
        migrations.AlterField(
            model_name='monthlyseries',
            name='region',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='monthly_series', to='metweather.region'),
        ),
        migrations.AlterField(
            model_name='monthlyseries',
            name='year',
            field=models.IntegerField(db_index=True),
        ),
        migrations.AlterField(
            model_name='region',
            name='code',
            field=models.CharField(max_length=64, unique=True),
        ),
        migrations.AlterField(
            model_name='region',
            name='name',
            field=models.CharField(max_length=200),
        ),
        migrations.AddIndex(
            model_name='monthlyseries',
            index=models.Index(fields=['region', 'parameter', 'year'], name='metweather__region__4344de_idx'),
        ),
        migrations.AddIndex(
            model_name='monthlyseries',
            index=models.Index(fields=['parameter', 'year', 'month'], name='metweather__paramet_fe20c8_idx'),
        ),
    ]
