# Generated by Django 5.2.5 on 2025-08-19 09:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metweather', '0007_delete_parameter_alter_monthlyseries_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='monthlyseries',
            options={},
        ),
        migrations.RemoveIndex(
            model_name='monthlyseries',
            name='metweather__region__4344de_idx',
        ),
        migrations.RemoveIndex(
            model_name='monthlyseries',
            name='metweather__paramet_fe20c8_idx',
        ),
        migrations.AlterField(
            model_name='monthlyseries',
            name='month',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='monthlyseries',
            name='parameter',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='monthlyseries',
            name='region',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='metweather.region'),
        ),
        migrations.AlterField(
            model_name='monthlyseries',
            name='year',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='region',
            name='code',
            field=models.CharField(max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name='region',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
