# Generated by Django 5.2.5 on 2025-08-19 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metweather', '0008_alter_monthlyseries_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='region',
            name='code',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
